---
- hosts: " {{ env }} "
  become: yes
  tasks:
    - name: set image var
      command: export IMAGE="suryabh/samplejavaapp:V1."{{ ver }}""
    - name: Create Dep
      command: yq eval '.spec.template.spec.containers[0].image = "'$IMAGE'"' vamsitestdep.yml | kubectl apply -f -
    - name: Crate SVC
      command: kubectl apply -f vamsitestsvc.yml
