---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: cont1
          image: suryabh/samplejavaapp:V1.9
          ports:
            - name: http
              containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31111
